# -------------------------
# Mongo Db Secret Env
# -------------------------
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: database
type: Opaque
data: # EncodeDB env base64 ( https://www.utilities-online.info/base64, https://hub.docker.com/_/mongo )
  db_password: UGFzc3dvcmQwMSQ=
  db_user_root: VXNlclJvb3QwMSQ=
